import 'package:proyecto_ed/model/book.dart';

List<Book> books = [
  Book(
    title: "Matemática discreta y lógica",
    authors: ["GRASSMANN, Winfried K", "TREMBLAY, J. P."],
    city: "Madrid",
    country: "España",
    publisher: "Prentice Hall",
    year: 2003,
    imagePath: "assets/libros/1.jpg",
    description: 
"De acuerdo con el plan de estudios, se indica que este libro contiene todos los temas para la asignatura de Estructuras Discretas.\n"
"\n1. Lógica proposicional y cálculo de predicados"
"\n2. Conjuntos, relaciones y pruebas matemáticas"
"\n3. Sistemas algebraicos"
"\n4. Teoría de gráficas"
"\n5. Teoría de la computabilidad",
  ),
  Book(
    title: "Discrete Mathematics",
    authors: ["JOHNSONBAUGH, Richard"],
    city: "London",
    country: "U.K.",
    publisher: "Prentice Hall",
    year: 2004,
    imagePath: "assets/libros/2.jpg",
  ),
  Book(
    title: "Algorithms: Sequential, Parallel, and Distributed",
    authors: ["KENNETH A. Berman", "JEROME L. Paul"],
    country: "U.S.A.",
    publisher: "Thomson",
    year: 2004,
    imagePath: "assets/libros/3.jpg",
  ),
  Book(
    title: "Discrete Mathematical Structures",
    authors: ["KOLMAN, Bernard"],
    country: "U.S.A.",
    publisher: "Prentice Hall",
    year: 2003,
    imagePath: "assets/libros/4.jpg",
  ),
  Book(
    title: "Elementos de matemáticas discretas",
    authors: ["LIU, C. L."],
    country: "México",
    publisher: "McGraw-Hill",
    year: 1995,
    imagePath: "assets/libros/5.jpg",
  ),
  Book(
    title: "Matemáticas discretas y sus aplicaciones",
    authors: ["ROSEN, Kenneth H."],
    edition: "5a. edición",
    country: "España",
    publisher: "McGraw-Hill",
    year: 2004,
    imagePath: "assets/libros/6.jpg",
  ),
  Book(
    title: "Matemáticas discretas con aplicación a las ciencias de la computación",
    authors: ["TREMBLAY, Jean-Paul", "MANOHAR, Ram"],
    translator: "RANGEL GUTIÉRREZ, Raymundo Hugo",
    country: "México",
    publisher: "CECSA",
    year: 2000,
    imagePath: "assets/libros/7.jpg",
  ),
  Book(
    title: "Matemáticas discretas con teoría de gráficas y combinatoria",
    authors: ["VEERARAJAN, T."],
    country: "México",
    publisher: "McGraw-Hill Interamericana",
    year: 2008,
    imagePath: "assets/libros/8.jpg",
  ),
  Book(
    title: "Introductory Discrete Mathematics",
    authors: ["BALAKRISHNAN, V. K."],
    city: "New York",
    country: "U.S.A.",
    publisher: "Dover",
    year: 1996,
    imagePath: "assets/libros/9.jpg",
  ),
  Book(
    title: "Matemáticas discretas",
    authors: ["BOGART, Kenneth P."],
    country: "México",
    publisher: "Limusa",
    year: 1998,
    imagePath: "assets/libros/10.jpg",
  ),
  Book(
    title: "Matemática discreta",
    authors: ["COMELLAS, Francesc"],
    country: "México",
    publisher: "Alfaomega",
    year: 2002,
    imagePath: "assets/libros/11.jpg",
  ),
  Book(
    title: "Discrete mathematics: elementary and beyond",
    authors: ["LOVASZ, Laszlo"],
    city: "New York",
    country: "U.S.A.",
    publisher: "Springer",
    year: 2003,
    imagePath: "assets/libros/12.jpg",
  ),
  Book(
    title: "Matemáticas discretas",
    authors: ["SCHEINERMAN, Edward"],
    country: "México",
    publisher: "Thomson Learning",
    year: 2001,
    imagePath: "assets/libros/13.jpg",
  ),
];
